@startuml Transition

/'
 ' Energy is a concept that can be produced.
 '/
abstract class Energy
Energy : production(float time) : float

/'
 ' Usage of an energy
 '/
abstract class Usage
Usage : consumption(float time) : float


/'
 ' Primary energy sources : easy to exploit, like petrol, coal, gas, burning wood.
 ' Straight forward transformation of the source to energy by burning, low tech for conversion.
 '/
class Source extends Energy, Usage

class BikeDynamo extends Source
BikeDynamo : production(float time) : float
BikeDynamo : consumption(float time) : float

/'
 ' Secondary energy source : transform something into electricity but with a device that needs to be build.
 ' More complex transformation of the source to energy by using a device, high tech for conversion.
 '/
class Converter extends Energy, Usage

/'
 ' Lighting is a usage of energy
 '/
class Lighting extends Usage
Lighting : consumption(float time) : float


/'
 ' A grid receives converge source of energies and make it availabe for usages
 '/
class Grid

@enduml